# Datan analysointi K2021 - Tehtävät kerta 3

Palauta ratkaisusi Moodleen, kun olet ensin testannut ratkaisusi toimivuuden Notebookilla tai omalla koneellasi. Kun olet palauttanut tehtäväsi Moodleen, ne arvioidaan pistein:
* 1,0 p. Vastaus oikein ensimmäisellä yrityksellä.
* 0,5 p. Vastaus oikein toisella yrityksellä.
* 0 p. Vastaus väärin kolmannella yrityksellä.

**Tee tehtävät ilman for-silmukoita tms.**

### 1. Päästöjen aiheuttajia

Tee funktio emissions(url), joka tekee järjestyksessä seuraavaa:
* lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
* tallentaa DataFrameen sarakkeet 'country' ja 'main activity sector name',
* poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
* laskee kuinka monta kertaa sarakkeen 'main activity sector name' eri arvot esiintyvät DataFramessa,
* tulostaa (viisi ensimmäistä riviä) järjestyksessä pienimmästä suurimpaan sarakkeen 'main activity sector name' arvojen lukumäärät.

Tässä tehtävässä url=https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv

Esimerkiksi, emissions(url) tulostaa:

| | | |
|:---|:---|:---|
|45 |Capture of greenhouse gases under Directive 2009/31/EC      | 14|
|46 |Transport of greenhouse gases under Directive 2009/31/EC    | 22|
|40 |Production of glyoxal and glyoxylic acid                    | 37|
|39 |Production of adipic acid                                   | 43|
|44 |Production of soda ash and sodium bicarbonate               |325|
|Name: sector, dtype: int64| | |

In [1]:
def emissions(url):
    # Kirjoita vastauksesi tähän alle:
    
    import pandas as pd
    import warnings
    warnings.filterwarnings("ignore", 'This pattern has match groups')


    # lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),

    data = pd.read_csv(url,
                  sep= '\t',
                   quoting=3
                  )

    data.columns = data.columns.str.strip('""')
    data['country'] = data['country'].replace(to_replace='"', value='', regex=True)
    data['year'] = data['year'].replace(to_replace='"', value='', regex=True)


    # tallentaa DataFrameen sarakkeet 'country' ja 'main activity sector name',
    df = data[['country', 'main activity sector name']]


    '''poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot:
    '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'''

    df1 = df[~df['main activity sector name'].str.contains("20-99 All stationary installations")]
    df2 = df1[~df1['main activity sector name'].str.contains("21-99 All industrial installations (excl. combustion)")]
    
    df2['sector'] = df2['main activity sector name']


    # laskee kuinka monta kertaa sarakkeen 'main activity sector name' eri arvot esiintyvät DataFramessa
    df3 = df2['sector'].value_counts(ascending=True)


    # tulostaa (viisi ensimmäistä riviä) järjestyksessä pienimmästä suurimpaan sarakkeen 'main activity sector name' arvojen lukumäärät.
    tulos = df3.head()
    # Älä kirjoita tähän muita print komentoja ennen viimeistä print(tulos) komentoa, koska tällöin vastauksesi saatetaan tulkita väärin.
    
    # Lopuksi vastauksesi tulostetaan tulos muuttujassa
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

45 Capture of greenhouse gases under Directive 2009/31/EC       14
46 Transport of greenhouse gases under Directive 2009/31/EC     22
40 Production of glyoxal and glyoxylic acid                     37
39 Production of adipic acid                                    43
44 Production of soda ash and sodium bicarbonate               325
Name: sector, dtype: int64

### 2. Päästöjen summaaminen

Tee funktio emissions(url), joka tekee järjestyksessä seuraavaa:
* lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
* tallentaa DataFrameen sarakkeet 'main activity sector name', 'value' ja 'year',
* poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
* tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
* laskee uuteen DataFrameen kuinka paljon ovat kokonaispäästöt sektoreittain (summa sarakkeesta 'values', jotka on ryhmitelty sarakkeen 'main activity sector name' mukaan),
* järjestää uuden DataFramen rivit suurimmasta pienimpään sarakkeen 'value' mukaan,
* tulostaa viisi ensimmäistä riviä DataFramesta siten, että sarake 'main activity sector name' on nimetty sarakkeeksi 'sector',
* huomaa, että sarake 'value' on ennen saraketta 'sector'.

Tässä tehtävässä url=https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv

Esimerkiksi, emissions(url) tulostaa:

|   | value        |                   sector             |
|:---|:---|:---|
|1  | 1.273006e+10 |              20 Combustion of fuels  |
|5  | 2.053915e+09 | 24  Production of pig iron or steel  |
|10 | 1.803550e+09 |     29 Production of cement clinker  |
|2  | 1.678130e+09 |         21  Refining of mineral oil  |
|0  | 5.644274e+08 |                         10 Aviation  |

In [229]:
def emissions(url):
    # Kirjoita vastauksesi tähän alle:
    
    data = pd.read_csv(url,
                  sep= '\t',
                   quoting=3
                  )

    data.columns = data.columns.str.strip('""')
    data['country'] = data['country'].replace(to_replace='"', value='', regex=True)
    data['year'] = data['year'].replace(to_replace='"', value='', regex=True)


    # tallentaa DataFrameen sarakkeet 'main activity sector name', 'value' ja 'year'
    df = data[['main activity sector name', 'value', 'year']]

    # poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '
    # '20-99 All stationary installations' 
    #'21-99 All industrial installations (excl. combustion)'
    df1 = df[~df['main activity sector name'].str.contains("20-99 All stationary installations",regex=True)]
    df2 = df1[~df1['main activity sector name'].astype(str).str.startswith('21-99')]

    # siivotaan dataframesta years-osiosta kaikki paitsi vuodet pois
    df2c = df2.copy()
    df2c['year'] = df2c['year'].convert_dtypes()
    mask = (df2['year'].str.len() <= 4)
    df3 = df2c.loc[mask]
    df4 = df3.copy()
    df4['year'] = df4['year'].apply(pd.to_numeric)


    # tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
    df5 = df4.loc[(df4['year'] >= 2010) & (df4['year'] <= 2015)]


    # laskee uuteen DataFrameen kuinka paljon ovat kokonaispäästöt sektoreittain (summa sarakkeesta 'values', jotka on ryhmitelty sarakkeen 'main activity sector name' mukaan),
    df6 = df5.copy()
    df6g = pd.DataFrame(df6.groupby('main activity sector name')['value'].sum())
    df6g.reset_index(inplace=True)

    # järjestää uuden DataFramen rivit suurimmasta pienimpään sarakkeen 'value' mukaan,
    df7 = df6g.sort_values(by='value',ascending=False)

    # tulostaa viisi ensimmäistä riviä DataFramesta siten, että sarake 'main activity sector name' on nimetty sarakkeeksi 'sector',
    df7.rename(columns = {'main activity sector name':'sector'}, inplace = True) 
    df8 = df7.reindex(columns= ['value', 'sector'])
    tulos = df8.head()
    # Älä kirjoita tähän muita print komentoja ennen viimeistä print(tulos) komentoa, koska tällöin vastauksesi saatetaan tulkita väärin.
    
    # Lopuksi vastauksesi tulostetaan tulos muuttujassa
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

           value                               sector
1   1.273006e+10               20 Combustion of fuels
5   2.053915e+09  24  Production of pig iron or steel
10  1.803550e+09      29 Production of cement clinker
2   1.678130e+09          21  Refining of mineral oil
0   5.644274e+08                          10 Aviation

### 3. Päästöjen muutokset vuosittain

Tee funktio emissions(url), joka tekee järjestyksessä seuraavaa:
* lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
* tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year',
* poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
* tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
* laskee uuteen DataFrameen kuinka paljon päästöjä on ollut yhteensä vuosittain (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeen 'year' arvojen mukaan),
* laskee uuteen DataFrameen uuteen sarakkeeseen 'change' kuinka paljon päästöt muuttuivat prosentuaalisesti edellisestä vuodesta (huom! vuoden 2010 arvo saa olla NaN, koska vuoden 2009 arvot on suodatettu pois),
* pyöristää em. prosentuaalisen muutoksen yhden desimaalin tarkkuuteen,
* laskee DataFramen uuteen sarakkeeseen 'cumsum' kumulatiivisen päästöjen summan vuodesta 2010 vuoteen 2015,
* tulostaa edellä kuvatulla tavalla tuotetun DataFramen siten, että DataFramen indeksinä on 'year'.

Tässä tehtävässä url=https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv

Esimerkiksi, emissions(url) tulostaa:

| |emissions|  change        |cumsum |
|:---|:---|:---|:---|
|year     |                |       |                |
|2010  		|5.068290e+09  |   NaN | 5.068290e+09   |
|2011  		|3.505169e+09  | -30.8 | 8.573458e+09   |
|2012  		|3.788401e+09  |   8.1 | 1.236186e+10   |
|2013  		|2.833849e+09  | -25.2 | 1.519571e+10   |
|2014  		|2.891243e+09  |   2.0 | 1.808695e+10   |
|2015  		|3.341047e+09  |  15.6 | 2.142800e+10   |

In [219]:
def emissions(url):
    # Kirjoita vastauksesi tähän

    # lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t')

    import pandas as pd
    data = pd.read_csv(url
                  , sep='\t'
                ,quoting=3)

    data.columns = data.columns.str.strip('"')
    data['country'] = data['country'].replace(to_replace='"', value="", regex=True)
    data['year'] = data['year'].replace(to_replace='"', value="", regex=True)

    # tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year'
    df = data[['country_code','main activity sector name', 'value', 'year']]

    
    # poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)
    df1 = df[~df['main activity sector name'].str.contains("20-99 All stationary installations",regex=True)]
    df2 = df1[~df1['main activity sector name'].astype(str).str.startswith('21-99')]


    # siivotaan dataframesta years-osiosta kaikki paitsi vuodet pois
    df2c = df2.copy()
    df2c['year'] = df2c['year'].convert_dtypes()
    mask = (df2['year'].str.len() <= 4)
    df3 = df2c.loc[mask]
    df4 = df3.copy()
    df4['year'] = df4['year'].apply(pd.to_numeric)

    # tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
    df5 = df4.loc[(df4['year'] >= 2010) & (df4['year'] <= 2015)]

    # laskee uuteen DataFrameen kuinka paljon päästöjä on ollut yhteensä vuosittain 
    # (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeen 'year' arvojen mukaan)
    df6 = df5.copy()
    df6 = df6.groupby('year')['value'].sum()

    # laskee uuteen DataFrameen uuteen sarakkeeseen 'change' kuinka paljon päästöt muuttuivat prosentuaalisesti edellisestä vuodesta
    # (huom! vuoden 2010 arvo saa olla NaN, koska vuoden 2009 arvot on suodatettu pois),
    df7 = pd.DataFrame(df6)
    df7['change'] = df7['value'].pct_change()*100

    # pyöristää em. prosentuaalisen muutoksen yhden desimaalin tarkkuuteen,
    df7['change'] = df7['change'].round(decimals=1)

    # laskee DataFramen uuteen sarakkeeseen 'cumsum' kumulatiivisen päästöjen summan vuodesta 2010 vuoteen 2015
    df7['cumsum'] = df7['value'].cumsum()
    df7.rename(columns = {'value':'emissions'}, inplace = True) 

    # tulostaa edellä kuvatulla tavalla tuotetun DataFramen siten, että DataFramen indeksinä on 'year'.

    tulos = df7
    
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

         emissions  change        cumsum
year
2010  5.068290e+09     NaN  5.068290e+09
2011  3.505169e+09   -30.8  8.573458e+09
2012  3.788401e+09     8.1  1.236186e+10
2013  2.833849e+09   -25.2  1.519571e+10
2014  2.891243e+09     2.0  1.808695e+10
2015  3.341047e+09    15.6  2.142800e+10

### 4. Suurimmat kokonaispäästöt maittain

Tee funktio emissions(url), joka tekee järjestyksessä seuraavaa:
* lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
* tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year',
* poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
* tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
* laskee uuteen DataFrameen kuinka paljon päästöjä kukin maa on tuottanut minäkin vuonna (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeiden 'country_code' ja 'year' mukaan),
* tallentaa uuteen DataFrameen kunkin maan (sarake 'country_code') suurimmat päästöt (sarake 'value') ja päästön tuottamisvuoden (sarake 'year'),
* järjestää em. DataFramen rivit suurimmasta pienimpään sarakkeen 'value' mukaan,
* nimeää sarakkeen 'country_code' sarakkeeksi 'ccode',
* tarvittaessa järjestää sarakkeet järjestykseen 'ccode', 'year', 'value' ja tulostaa viisi ensimmäistä riviä.

**Vinkki:** Tutki tarvittaessa pandasin groupby metodin [kuvausta](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html).

Tässä tehtävässä url=https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv

Esimerkiksi, emissions(url) tulostaa:

| |ccode | year |    value |
|:---|:---|:---|:---|
|30    | DE   |	2010 | 1.298336e+09 |
|66    | GB   |	2010 | 6.420594e+08 |
|50    | ES   |	2012 | 5.579101e+08 |
|150   | PL   |	2010 | 4.605025e+08 |
|102   | IT   |	2010 | 4.505878e+08 |

In [94]:
# lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
url = 'https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
data = pd.read_csv(url,
                  sep='\t',
                  quoting=3)

data.columns = data.columns.str.strip('"')
data['country'] = data['country'].replace(to_replace='"', value="", regex=True)
data['year'] = data['year'].replace(to_replace='"', value="", regex=True)


# tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year',
df = data[['country_code','main activity sector name', 'value', 'year']]


# poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)
df1 = df[~df['main activity sector name'].str.contains("20-99 All stationary installations",regex=True)]
df2 = df1[~df1['main activity sector name'].astype(str).str.startswith('21-99')]


# siivotaan dataframesta years-osiosta kaikki paitsi vuodet pois
df2c = df2.copy()
df2c['year'] = df2c['year'].convert_dtypes()
mask = (df2['year'].str.len() <= 4)
df3 = df2c.loc[mask]
df4 = df3.copy()
df4['year'] = df4['year'].apply(pd.to_numeric)

# tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
df5 = df4.loc[(df4['year'] >= 2010) & (df4['year'] <= 2015)]

# laskee uuteen DataFrameen kuinka paljon päästöjä kukin maa on tuottanut minäkin vuonna 
# (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeiden 'country_code' ja 'year' mukaan
df6 = df5.copy()
emission_country = pd.DataFrame(df6.groupby(['country_code','year'], as_index=False)['value'].sum()).sort_values(by='value', ascending=False)


# tallentaa uuteen DataFrameen kunkin maan (sarake 'country_code') suurimmat päästöt (sarake 'value') ja päästön tuottamisvuoden (sarake 'year')
agg_func_max = {'value': ['max', 'idxmax']}
df8 = emission_country.groupby(['country_code'], as_index=False).agg(agg_func_max)
df9 = df8.reset_index()


# poistetaan multiindex, joka syntyi edellisessä vaiheessa
df9.columns = list(map(''.join, df9.columns.values))


# määritetään vuosisarake idxmaxin avulla, haetaan vuosiluvut aiemmasta taulukosta
df9['year'] = emission_country.loc[df9['valueidxmax'], 'year'].values


# asetetaan idxmax arvot indekseiksi
df10 = df9.set_index('valueidxmax')
df10.index.name = None


# järjestää em. DataFramen rivit suurimmasta pienimpään sarakkeen 'value' mukaan,
df10.sort_values(by='valuemax', ascending=False, inplace=True)


# nimeää sarakkeen 'country_code' sarakkeeksi 'ccode'
df10.rename(columns = {'country_code':'ccode', 'valuemax':'value'}, inplace = True)


# poistetaan 'index'-sarake
df11 = df10.drop(['index'], axis=1)


tulos = df11.head()

In [97]:
def emissions(url):
    # Kirjoita vastauksesi tähän
    # lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
    data = pd.read_csv(url,
                  sep='\t',
                  quoting=3)

    data.columns = data.columns.str.strip('"')
    data['country'] = data['country'].replace(to_replace='"', value="", regex=True)
    data['year'] = data['year'].replace(to_replace='"', value="", regex=True)


    # tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year',
    df = data[['country_code','main activity sector name', 'value', 'year']]


    # poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)
    df1 = df[~df['main activity sector name'].str.contains("20-99 All stationary installations",regex=True)]
    df2 = df1[~df1['main activity sector name'].astype(str).str.startswith('21-99')]


    # siivotaan dataframesta years-osiosta kaikki paitsi vuodet pois
    df2c = df2.copy()
    df2c['year'] = df2c['year'].convert_dtypes()
    mask = (df2['year'].str.len() <= 4)
    df3 = df2c.loc[mask]
    df4 = df3.copy()
    df4['year'] = df4['year'].apply(pd.to_numeric)

    # tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
    df5 = df4.loc[(df4['year'] >= 2010) & (df4['year'] <= 2015)]

    # laskee uuteen DataFrameen kuinka paljon päästöjä kukin maa on tuottanut minäkin vuonna 
    # (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeiden 'country_code' ja 'year' mukaan
    df6 = df5.copy()
    emission_country = pd.DataFrame(df6.groupby(['country_code','year'], as_index=False)['value'].sum()).sort_values(by='value', ascending=False)


    # tallentaa uuteen DataFrameen kunkin maan (sarake 'country_code') suurimmat päästöt (sarake 'value') ja päästön tuottamisvuoden (sarake 'year')
    agg_func_max = {'value': ['max', 'idxmax']}
    df8 = emission_country.groupby(['country_code'], as_index=False).agg(agg_func_max)
    df9 = df8.reset_index()


    # poistetaan multiindex, joka syntyi edellisessä vaiheessa
    df9.columns = list(map(''.join, df9.columns.values))


    # määritetään vuosisarake idxmaxin avulla, haetaan vuosiluvut aiemmasta taulukosta
    df9['year'] = emission_country.loc[df9['valueidxmax'], 'year'].values


    # asetetaan idxmax arvot indekseiksi
    df10 = df9.set_index('valueidxmax')
    df10.index.name = None


    # järjestää em. DataFramen rivit suurimmasta pienimpään sarakkeen 'value' mukaan,
    df10.sort_values(by='valuemax', ascending=False, inplace=True)


    # nimeää sarakkeen 'country_code' sarakkeeksi 'ccode'
    df10.rename(columns = {'country_code':'ccode', 'valuemax':'value'}, inplace = True)


    # poistetaan 'index'-sarake
    df11 = df10.drop(['index'], axis=1)
    

    # järjestetään sarakkeet oikeaan järjestykseen ja tulostetaan viisi ensimmäistä riviä
    tulos = df11[['ccode', 'year', 'value']].head()
    
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

    ccode  year         value
30     DE  2010  1.298336e+09
66     GB  2010  6.420594e+08
50     ES  2012  5.579101e+08
150    PL  2010  4.605025e+08
102    IT  2010  4.505878e+08

### 5. Toiseksi suurimmat kokonaispäästöt maittain

Tee funktio emissions(url), joka tekee järjestyksessä seuraavaa:
* lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
* tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year',
* poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
* tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
* laskee uuteen DataFrameen kuinka paljon päästöjä kukin maa on tuottanut minäkin vuonna (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeiden 'country_code' ja 'year' mukaan),

* tallentaa uuteen DataFrameen kunkin maan (sarake 'country_code') **toiseksi** suurimmat päästöt (sarake 'value') ja päästön tuottamisvuoden (sarake 'year'),
* järjestää em. DataFramen rivit suurimmasta pienimpään sarakkeen 'value' mukaan,
* nimeää sarakkeen 'country_code' sarakkeeksi 'ccode',
* tarvittaessa järjestää sarakkeet järjestykseen 'ccode', 'year', 'value' ja tulostaa viisi ensimmäistä riviä.

**Vinkkejä:** 
* Tutki tarvittaessa pandasin [groupby](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html) ja [agg](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.agg.html) metodien kuvauksia.
* Jos käytät pandasin agg metodin argumenttina funktiota, niin tulee funktion sisällä etsiä toiseksi suurin arvo .iloc ominaisuudella (Tämä on tärkeää etenkin tehtävän Moodle palautuksen yhteydessä). 

Tässä tehtävässä url=https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv

Esimerkiksi, emissions(url) tulostaa:

| |ccode | year |    value |
|:---|:---|:---|:---|
|33    | DE  |2013  |1.073414e+09|
|49    | ES  |2011  |5.561922e+08|
|152   | PL  |2012  |4.348634e+08|
|67    | GB  |2011  |4.252068e+08|
|62    | FR  |2012  |3.104471e+08|

In [26]:
def emissions(url):
    # Kirjoita vastauksesi tähän
    # lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
    import pandas as pd
    data = pd.read_csv(url,
                  sep='\t',
                  quoting=3)

    data.columns = data.columns.str.strip('"')
    data['country'] = data['country'].replace(to_replace='"', value="", regex=True)
    data['year'] = data['year'].replace(to_replace='"', value="", regex=True)


    # tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year',
    df = data[['country_code','main activity sector name', 'value', 'year']]


    # poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)
    df1 = df[~df['main activity sector name'].str.contains("20-99 All stationary installations",regex=True)]
    df2 = df1[~df1['main activity sector name'].astype(str).str.startswith('21-99')]


    # siivotaan dataframesta years-osiosta kaikki paitsi vuodet pois
    df2c = df2.copy()
    df2c['year'] = df2c['year'].convert_dtypes()
    mask = (df2['year'].str.len() <= 4)
    df3 = df2c.loc[mask]
    df4 = df3.copy()
    df4['year'] = df4['year'].apply(pd.to_numeric)

    # tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
    df5 = df4.loc[(df4['year'] >= 2010) & (df4['year'] <= 2015)]

    # laskee uuteen DataFrameen kuinka paljon päästöjä kukin maa on tuottanut minäkin vuonna 
    # (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeiden 'country_code' ja 'year' mukaan
    df6 = df5.copy()
    e_country = df6.groupby(['country_code','year'], as_index=False)['value'].sum().sort_values(by='value', ascending=False)


    # tallentaa uuteen DataFrameen kunkin maan (sarake 'country_code') toiseksi suurimmat päästöt (sarake 'value') ja päästön tuottamisvuoden (sarake 'year')

    # funktio, jolla valitaan toinen alkio serieksestä
    def toka(x):
        return x.iloc[1]

    # funktio, jonka avulla saadaan mukaan indeksi edellisen funktion palautteelle
    def toka_index(x):
        return str(x.index[1])

    # groupby-metodi jonne asetellaan em. funktiot aiemmin määritetyillä ehdoilla
    df15 = e_country.groupby('country_code', as_index=False)['value'].agg([toka, toka_index]).sort_values(by='toka', ascending=False).reset_index()


    # nimeää sarakkeen 'country_code' sarakkeeksi 'ccode'
    df16 = df15.copy()
    df16.rename(columns = {'country_code':'ccode', 'toka':'value'}, inplace = True)


    # yhdistetään 'year'-sarake kokonaisuuteen
    df17 = pd.merge(df16,e_country, how='left', left_on='value', right_on='value').set_index(df15['toka_index'])
    df17.index.name = None

    # pudotetaan turhat sarakkeet
    df18 = df17.drop(['country_code', 'toka_index'], axis=1)


    tulos = df18[['ccode', 'year', 'value']].head()
    
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

    ccode  year         value
33     DE  2013  1.073414e+09
49     ES  2011  5.561922e+08
152    PL  2012  4.348634e+08
67     GB  2011  4.252068e+08
62     FR  2012  3.104471e+08