## Datan analysointi K2021 - Tehtävät kerta 1

Palauta ratkaisusi Moodleen, kun olet ensin testannut ratkaisusi toimivuuden Notebookilla tai omalla koneellasi. Kun olet palauttanut tehtäväsi Moodleen, ne arvioidaan pistein:
* 1,0 p. Vastaus oikein ensimmäisellä yrityksellä.
* 0,5 p. Vastaus oikein toisella yrityksellä.
* 0 p. Vastaus väärin kolmannella yrityksellä.

**Tee tehtävät ilman for-silmukoita tms.**

## 1. NumPy-taulukot  - kappaleen lähtönopeus

Kappaleen lähtönopeuden laskemiseksi on mitattu seuraava data:
* $\text{kulma} = \text{[10, 15, 20, 25, 30]}$
* $\text{kantama} = \text{[22.7, 21.9, 26.1, 28.8, 29.8]},$

missä $\text{kulma}$ on vaakatason ja kappaleen lähtönopeusvektorin välinen kulma asteina ja $\text{kantama}$ on kappaleen lentomatka yksiköissä cm.

Kappaleen lähtönopeus on silloin
$$
\text{nopeus}=\sqrt{\frac{\text{kantama}\cdot 9.82\ \text{m}/\text{s}^2}{\sin{\left( 2\cdot \text{kulma} \right)}}}.
$$

Kirjoita python funktio **nopeus(kulma, kantama)**, joka otta argumenteikseen python listat (kulma ja kantama) ja **tulostaa** lopuksi yllä olevalla kaavalla lasketun parametrin **nopeus**.

Käytä [numpy taulukoiden funktioita](https://numpy.org/doc/stable/reference/ufuncs.html) ratkaisussasi. Anna vastauksesi yksiköissä m/s. Sinun tarvitsee ottaa käyttöön ainoastaan annettu kaava sekä tehdä tarvittavat yksikkömuunnokset.

Funktion kutsun **nopeus(kulma, kantama)** em. kulma ja kantama taulukoilla pitäisi palauttaa:\
[2.55295306 2.07392382 1.99683532 1.92143193 1.83822454]

In [8]:
import numpy as np

# Voit testata funktiotasi seuraavalla lähtödatalla:
kulma = [10, 15, 20, 25, 30]
kantama = [22.7, 21.9, 26.1, 28.8, 29.8]

def nopeus(kulma, kantama):
    # Kirjoita vastauksesi tämän funktiorakenteen sisälle:
        # muutetaan parametrit oikeaan muotoon
    kulma_arr = np.array(kulma)
    kantama_arr_cm = np.array(kantama)
    
    # muutetaan kantama (cm) metreiksi (m)
    kantama_arr_m = kantama_arr_cm / 100
    
    # muutetaan kulma (asteet) radiaaneksi
    
    kulma_arr_rad = np.radians(kulma_arr)
    
    # laskukaava
    
    m = kantama_arr_m * 9.82
    k = np.sin(2*kulma_arr_rad)
    nopeus = np.sqrt(m/k)
    
    
    

    
    # Älä kirjoita missään tapauksessa muita print komentoja tämän rakenteen sisälle, koska silloin vastauksesi tulkitaan virheelliseksi.
    
    # Lopuksi tulostetaan määrittämäsi numpy taulukko nopeus:
    print(nopeus)

# Ennen tehtävän palauttamista Moodleen, kokeile sitä seuraavasti:
nopeus(kulma, kantama)

[2.55295306 2.07392382 1.99683532 1.92143193 1.83822454]

In [9]:
import numpy as np

kulma = [10, 15, 20, 25, 30]
kantama = [22.7, 21.9, 26.1, 28.8, 29.8]

def nopeus(kulma, kantama):
    # Kirjoita vastauksesi tämän funktiorakenteen sisälle:
    
    # muutetaan parametrit oikeaan muotoon
    kulma_arr = np.array(kulma)
    kantama_arr_cm = np.array(kantama)
    
    # muutetaan kantama (cm) metreiksi (m)
    kantama_arr_m = kantama_arr_cm / 100
    
    # muutetaan kulma (asteet) radiaaneksi
    
    kulma_arr_rad = np.radians(kulma_arr)
    
    # laskukaava
    
    m = kantama_arr_m * 9.82
    k = np.sin(2*kulma_arr_rad)
    nopeus = np.sqrt(m/k)
    
    
    print(nopeus)
    
nopeus(kulma, kantama)

[2.55295306 2.07392382 1.99683532 1.92143193 1.83822454]

## 2. Looginen valinta ja laskenta NumPy taulukoilla

Tee NumPy taulukoita hyväksikäyttäen funktio **vertaa(luvut1, luvut2)**, joka ottaa argumenteikseen python taulukot (luvut1 ja luvut2) ja tekee seuraavat laskutoimitukset:
* Luodaan taulukoista "luvut1" ja "luvut2" uudet saman kokoiset NumPy taulukot, joissa on samat lukuarvot.
* Jatkolaskut tehdään pelkästään luotujen NumPy taulukoiden avulla.
* Jos taulukossa "luvut1" alkio rivillä i ja sarakkeessa j on pienempi kuin taulukossa "luvut2" alkio rivillä i ja sarakkeessa j, tulostetaan taulukkoon "luvut1" riville i ja sarakkeeseen j kokonaisluku "-1".
* Lasketaan "tulos" taulukoksi alkioittainen summa "luvut1" ja "luvut2" taulukoiden arvoista.
* Alkioittaisessa summassa lasketaan yhteen summattavien taulukoiden alkiot, joilla on sama rivi- ja sarakeindeksi.
* Annetaan vastaukseksi "tulos" taulukko tulosteena.

Funktiolle **vertaa** annettavat (3 x 3) python taulukot ovat:
* luvut1 = [[12, 2, 4], [5, 1, 2], [9, 3, 45]]
* luvut2 = [[11, 9, 32], [2, 3, 1], [0, 3, 10]]

**Esimerkiksi** vertaa(luvut1, luvut2) tulostaa:
<img src="https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta1/.s20harkkatd/teht2.png" width="110"/>

**Huom!** Tässä tehtävässä ei saa käyttää for silmukoita. Tutustu NumPy [taulukon suodatukseen Boolean taulukon avulla](https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta1/s20kerta1.html#7).

In [10]:
# Voit testata funktiotasi seuraavalla lähtödatalla:
luvut1 = [[12, 2, 4], [5, 1, 2], [9, 3, 45]]
luvut2 = [[11, 9, 32], [2, 3, 1], [0, 3, 10]]

def vertaa(luvut1, luvut2):
    # Kirjoita vastauksesi tämän funktiorakenteen sisälle:

    # Älä kirjoita missään tapauksessa muita print komentoja tämän rakenteen sisälle, koska silloin vastauksesi tulkitaan virheelliseksi.
    
    print(tulos)

# Ennen tehtävän palauttamista Moodleen, kokeile sitä seuraavasti:
vertaa(luvut1, luvut2)

NameError: name 'tulos' is not defined

## 3. DataFrame - Veikkausliiga

Alla on sisäkkäisisitä sanakirjoista koostuva tietorakenne, jossa on jalkapallon Veikkausliigajoukkueiden sarjasijoitukset 1990-2019.

Tee sanakirjasta DataFrame, jossa vuodet ovat riviotsikoita ja joukkueet sarakeotsikoita. 

Suodata ja tulosta sitten DataFramesta seuraava näkymä (älä valitse rivejä "käsin"):
* Jos data sisältää puuttuvia arvoja NaN, niin sijoita näiden paikalle lukuarvo 0.
* HJK:n sijoitus on ollut 3 parhaan joukossa.
* Valitse rivit vuosilta 1995-2005 ja RoPS:n, HJK:n ja Ilveksen sarakkeet.
* Kaikki yli 10 olevat sijoitukset korvataan merkkijonolla 'yli 10'.

In [5]:
veikkausliiga = {1990: {'HJK': 1,'Kuusysi': 2,'MP': 3,'Reipas': 4,'RoPS': 5,'KuPS': 6,'TPS': 7,'Haka': 8,'Ilves': 9,'OTP': 10,'KPV': 11,'Kumu': 12},
1991: {'Kuusysi': 1,'MP': 2,'Haka': 3,'Jaro': 4,'HJK': 5,'Ilves': 6,'RoPS': 7,'Jazz': 8,'TPS': 9,'KuPS': 10,'OTP': 11,'Reipas': 12},
1992: {'HJK': 1,'Kuusysi': 2,'Jazz': 3,'MYPA': 4,'Jaro': 5,'Haka': 6,'RoPS': 7,'Ilves': 8,'TPS': 9,'MP': 10,'FC/AC Oulu': 11,'KuPS': 12},
1993: {'Jazz': 1,'MYPA': 2,'HJK': 3,'Kuusysi': 4,'FinnPa': 5,'TPV': 6,'RoPS': 7,'TPS': 8,'MP': 9,'Haka': 10,'Jaro': 11,'Ilves': 12},
1994: {'TPV': 1,'MYPA': 2,'HJK': 3,'Jazz': 4,'RoPS': 5,'Haka': 6,'Jaro': 7,'TPS': 8,'Kuusysi': 9,'FinnPa': 10,'MP': 11,'Ilves': 12,'FC/AC Oulu': 13,'KuPS': 14},
1995: {'Haka': 1,'MYPA': 2,'HJK': 3,'Jazz': 4,'Jaro': 5,'TPS': 6,'Ilves': 7,'FinnPa': 8,'RoPS': 9,'VPS': 10,'MP': 11,'TPV': 12,'Kuusysi': 13,'Ponnistus': 14},
1996: {'Jazz': 1,'MYPA': 2,'TPS': 3,'FinnPa': 4,'Jaro': 5,'Inter': 6,'VPS': 7,'RoPS': 8,'HJK': 9,'Ilves': 10,'Haka': 11,'MP': 12},
1997: {'HJK': 1,'VPS': 2,'FinnPa': 3,'TPS': 4,'MYPA': 5,'RoPS': 6,'Jazz': 7,'Jaro': 8,'TP-Seinäjoki': 9,'Inter': 10},
1998: {'Haka': 1,'VPS': 2,'PK-35': 3,'HJK': 4,'Jazz': 5,'TPS': 6,'MYPA': 7,'RoPS': 8,'FinnPa': 9,'Jaro': 10},
1999: {'Haka': 1,'HJK': 2,'MYPA': 3,'Jokerit': 4,'Inter': 5,'Jazz': 6,'KooTeePee': 7,'RoPS': 8,'TPS': 9,'Lahti': 10,'VPS': 11,'TPV': 12},
2000: {'Haka': 1,'Jokerit': 2,'MYPA': 3,'HJK': 4,'Jazz': 5,'TamU': 6,'Inter': 7,'Lahti': 8,'RoPS': 9,'VPS': 10,'TPS': 11,'KooTeePee': 12},
2001: {'TamU': 1,'HJK': 2,'MYPA': 3,'Haka': 4,'Inter': 5,'VPS': 6,'Atlantis': 7,'KuPS': 8,'Lahti': 9,'Jazz': 10,'Jokerit': 11,'RoPS': 12},
2002: {'HJK': 1,'MYPA': 2,'Haka': 3,'Allianssi': 4,'TamU': 5,'Inter': 6,'Jaro': 7,'Lahti': 8,'KuPS': 9,'Hämeenlinna': 10,'VPS': 11,'Jazz': 12},
2003: {'HJK': 1,'Haka': 2,'TamU': 3,'MYPA': 4,'Lahti': 5,'Allianssi': 6,'Inter': 7,'Jaro': 8,'TPS': 9,'Jokerit': 10,'Hämeenlinna': 11,'Jazz': 12,'KooTeePee': 13,'KuPS': 14},
2004: {'Haka': 1,'Allianssi': 2,'TamU': 3,'Inter': 4,'TPS': 5,'HJK': 6,'Lahti': 7,'MYPA': 8,'KooTeePee': 9,'TP-47': 10,'Jaro': 11,'RoPS': 12,'Jazz': 13,'Hämeenlinna': 14},
2005: {'MYPA': 1,'HJK': 2,'TamU': 3,'Haka': 4,'Inter': 5,'Lahti': 6,'Allianssi': 7,'KooTeePee': 8,'TPS': 9,'KuPS': 10,'Jaro': 11,'IFK Mariehamn': 12,'RoPS': 13,'TP-47': 14},
2006: {'TamU': 1,'HJK': 2,'Haka': 3,'Honka': 4,'IFK Mariehamn': 5,'MYPA': 6,'TPS': 7,'Lahti': 8,'VPS': 9,'Inter': 10,'KooTeePee': 11,'Jaro': 12,'KuPS': 13},
2007: {'TamU': 1,'Haka': 2,'TPS': 3,'Honka': 4,'MYPA': 5,'IFK Mariehamn': 6,'HJK': 7,'Lahti': 8,'Inter': 9,'VPS': 10,'Jaro': 11,'KooTeePee': 12,'Viikingit': 13,'FC/AC Oulu': 14},
2008: {'Inter': 1,'Honka': 2,'Lahti': 3,'HJK': 4,'MYPA': 5,'TPS': 6,'TamU': 7,'Haka': 8,'Jaro': 9,'RoPS': 10,'VPS': 11,'IFK Mariehamn': 12,'KuPS': 13,'KooTeePee': 14},
2009: {'HJK': 1,'Honka': 2,'TPS': 3,'IFK Mariehamn': 4,'Inter': 5,'Haka': 6,'TamU': 7,'VPS': 8,'MYPA': 9,'Jaro': 10,'Lahti': 11,'KuPS': 12,'JJK': 13,'RoPS': 14},
2010: {'HJK': 1,'KuPS': 2,'TPS': 3,'Honka': 4,'Jaro': 5,'Inter': 6,'TamU': 7,'Haka': 8,'MYPA': 9,'VPS': 10,'FC/AC Oulu': 11,'IFK Mariehamn': 12,'JJK': 13,'Lahti': 14},
2011: {'HJK': 1,'Inter': 2,'JJK': 3,'Honka': 4,'TPS': 5,'KuPS': 6,'IFK Mariehamn': 7,'MYPA': 8,'VPS': 9,'Haka': 10,'Jaro': 11,'RoPS': 12},
2012: {'HJK': 1,'Inter': 2,'TPS': 3,'IFK Mariehamn': 4,'Lahti': 5,'MYPA': 6,'Honka': 7,'VPS': 8,'JJK': 9,'KuPS': 10,'Jaro': 11,'Haka': 12},
2013: {'HJK': 1,'Honka': 2,'VPS': 3,'IFK Mariehamn': 4,'Lahti': 5,'MYPA': 6,'KuPS': 7,'TPS': 8,'Inter': 9,'Jaro': 10,'RoPS': 11,'JJK': 12},
2014: {'HJK': 1,'SJK': 2,'Lahti': 3,'VPS': 4,'IFK Mariehamn': 5,'Jaro': 6,'KuPS': 7,'MYPA': 8,'Inter': 9,'RoPS': 10,'Honka': 11,'TPS': 12},
2015: {'SJK': 1,'RoPS': 2,'HJK': 3,'Inter': 4,'Lahti': 5,'IFK Mariehamn': 6,'HIFK': 7,'Ilves': 8,'KuPS': 9,'VPS': 10,'KooTeePee': 11,'Jaro': 12},
2016: {'IFK Mariehamn': 1,'HJK': 2,'SJK': 3,'VPS': 4,'Ilves': 5,'RoPS': 6,'KuPS': 7,'Lahti': 8,'PS Kemi': 9,'HIFK': 10,'Inter': 11,'PK-35': 12},
2017: {'HJK': 1,'KuPS': 2,'Ilves': 3,'Lahti': 4,'IFK Mariehamn': 5,'SJK': 6,'RoPS': 7,'VPS': 8,'Inter': 9,'PS Kemi': 10,'HIFK': 11,'JJK': 12},
2018: {'HJK': 1,'RoPS': 2,'KuPS': 3,'Honka': 4,'Ilves': 5,'VPS': 6,'Inter': 7,'Lahti': 8,'SJK': 9,'IFK Mariehamn': 10,'TPS': 11,'PS Kemi': 12},
2019: {'KuPS': 1,'Inter': 2,'Honka': 3,'Ilves': 4,'HJK': 5,'IFK Mariehamn': 6,'HIFK': 7,'Lahti': 8,'SJK': 9,'RoPS': 10,'KPV': 11,'VPS': 12}}

# Kirjoita vastauksesi tähän, jossa hyödynnät pandas DataFramea.
import pandas as pd
# luodaan DataFrame annetusta datasta

data = veikkausliiga
df = pd.DataFrame(data)

# Jos data sisältää puuttuvia arvoja NaN, niin sijoita näiden paikalle lukuarvo 0
df.fillna(float(0),inplace=True)

# vuodet ovat riviotsikoita ja joukkueet sarakeotsikoita.
df = df.T

# kaikista tietotyypeistä lukuarvoja
# df = df.astype('object')
#df.apply(pd.to_numeric, errors='ignore')
df.rename(columns = {'HJK':' HJK'}, inplace = True)
df.rename(columns = {'Ilves':' Ilves'}, inplace = True)

# Pudotetaan vuodet muut vuodet, paitsi jolloin HJK on ollut top3-joukossa

index_names = df[df[' HJK'] > 3 ].index
df.drop(index_names, inplace = True)

# Kaikki yli 10 olevat sijoitukset korvataan merkkijonolla 'yli 10'
df[df>10] = "yli 10"


# df = df.astype('float64', errors='ignore')
pd.set_option('precision', 0)

# Valitse rivit vuosilta 1995-2005 ja RoPS:n, HJK:n ja Ilveksen sarakkeet.
query = df.loc[1995:2005, ["RoPS", " HJK", " Ilves"]]

# tulostetaan hausta viisi ensimmäistä riviä
tulos = query.head(5)
#Älä kirjoita tähän muita print komentoja kuin viimeillä rivillä, koska ne antavat sinulle automaattitarkistuksessa virheellisen vastauksen.

# Muokkaa vastauksesi siten, että se tulostetaan alla olevan tulos muuttujan avulla:
print(tulos)

        RoPS   HJK  Ilves
1995       9     3      7
1997       6     1      0
1999       8     2      0
2001  yli 10     2      0
2002       0     1      0

In [243]:
veikkausliiga = {1990: {'HJK': 1,'Kuusysi': 2,'MP': 3,'Reipas': 4,'RoPS': 5,'KuPS': 6,'TPS': 7,'Haka': 8,'Ilves': 9,'OTP': 10,'KPV': 11,'Kumu': 12},
1991: {'Kuusysi': 1,'MP': 2,'Haka': 3,'Jaro': 4,'HJK': 5,'Ilves': 6,'RoPS': 7,'Jazz': 8,'TPS': 9,'KuPS': 10,'OTP': 11,'Reipas': 12},
1992: {'HJK': 1,'Kuusysi': 2,'Jazz': 3,'MYPA': 4,'Jaro': 5,'Haka': 6,'RoPS': 7,'Ilves': 8,'TPS': 9,'MP': 10,'FC/AC Oulu': 11,'KuPS': 12},
1993: {'Jazz': 1,'MYPA': 2,'HJK': 3,'Kuusysi': 4,'FinnPa': 5,'TPV': 6,'RoPS': 7,'TPS': 8,'MP': 9,'Haka': 10,'Jaro': 11,'Ilves': 12},
1994: {'TPV': 1,'MYPA': 2,'HJK': 3,'Jazz': 4,'RoPS': 5,'Haka': 6,'Jaro': 7,'TPS': 8,'Kuusysi': 9,'FinnPa': 10,'MP': 11,'Ilves': 12,'FC/AC Oulu': 13,'KuPS': 14},
1995: {'Haka': 1,'MYPA': 2,'HJK': 3,'Jazz': 4,'Jaro': 5,'TPS': 6,'Ilves': 7,'FinnPa': 8,'RoPS': 9,'VPS': 10,'MP': 11,'TPV': 12,'Kuusysi': 13,'Ponnistus': 14},
1996: {'Jazz': 1,'MYPA': 2,'TPS': 3,'FinnPa': 4,'Jaro': 5,'Inter': 6,'VPS': 7,'RoPS': 8,'HJK': 9,'Ilves': 10,'Haka': 11,'MP': 12},
1997: {'HJK': 1,'VPS': 2,'FinnPa': 3,'TPS': 4,'MYPA': 5,'RoPS': 6,'Jazz': 7,'Jaro': 8,'TP-Seinäjoki': 9,'Inter': 10},
1998: {'Haka': 1,'VPS': 2,'PK-35': 3,'HJK': 4,'Jazz': 5,'TPS': 6,'MYPA': 7,'RoPS': 8,'FinnPa': 9,'Jaro': 10},
1999: {'Haka': 1,'HJK': 2,'MYPA': 3,'Jokerit': 4,'Inter': 5,'Jazz': 6,'KooTeePee': 7,'RoPS': 8,'TPS': 9,'Lahti': 10,'VPS': 11,'TPV': 12},
2000: {'Haka': 1,'Jokerit': 2,'MYPA': 3,'HJK': 4,'Jazz': 5,'TamU': 6,'Inter': 7,'Lahti': 8,'RoPS': 9,'VPS': 10,'TPS': 11,'KooTeePee': 12},
2001: {'TamU': 1,'HJK': 2,'MYPA': 3,'Haka': 4,'Inter': 5,'VPS': 6,'Atlantis': 7,'KuPS': 8,'Lahti': 9,'Jazz': 10,'Jokerit': 11,'RoPS': 12},
2002: {'HJK': 1,'MYPA': 2,'Haka': 3,'Allianssi': 4,'TamU': 5,'Inter': 6,'Jaro': 7,'Lahti': 8,'KuPS': 9,'Hämeenlinna': 10,'VPS': 11,'Jazz': 12},
2003: {'HJK': 1,'Haka': 2,'TamU': 3,'MYPA': 4,'Lahti': 5,'Allianssi': 6,'Inter': 7,'Jaro': 8,'TPS': 9,'Jokerit': 10,'Hämeenlinna': 11,'Jazz': 12,'KooTeePee': 13,'KuPS': 14},
2004: {'Haka': 1,'Allianssi': 2,'TamU': 3,'Inter': 4,'TPS': 5,'HJK': 6,'Lahti': 7,'MYPA': 8,'KooTeePee': 9,'TP-47': 10,'Jaro': 11,'RoPS': 12,'Jazz': 13,'Hämeenlinna': 14},
2005: {'MYPA': 1,'HJK': 2,'TamU': 3,'Haka': 4,'Inter': 5,'Lahti': 6,'Allianssi': 7,'KooTeePee': 8,'TPS': 9,'KuPS': 10,'Jaro': 11,'IFK Mariehamn': 12,'RoPS': 13,'TP-47': 14},
2006: {'TamU': 1,'HJK': 2,'Haka': 3,'Honka': 4,'IFK Mariehamn': 5,'MYPA': 6,'TPS': 7,'Lahti': 8,'VPS': 9,'Inter': 10,'KooTeePee': 11,'Jaro': 12,'KuPS': 13},
2007: {'TamU': 1,'Haka': 2,'TPS': 3,'Honka': 4,'MYPA': 5,'IFK Mariehamn': 6,'HJK': 7,'Lahti': 8,'Inter': 9,'VPS': 10,'Jaro': 11,'KooTeePee': 12,'Viikingit': 13,'FC/AC Oulu': 14},
2008: {'Inter': 1,'Honka': 2,'Lahti': 3,'HJK': 4,'MYPA': 5,'TPS': 6,'TamU': 7,'Haka': 8,'Jaro': 9,'RoPS': 10,'VPS': 11,'IFK Mariehamn': 12,'KuPS': 13,'KooTeePee': 14},
2009: {'HJK': 1,'Honka': 2,'TPS': 3,'IFK Mariehamn': 4,'Inter': 5,'Haka': 6,'TamU': 7,'VPS': 8,'MYPA': 9,'Jaro': 10,'Lahti': 11,'KuPS': 12,'JJK': 13,'RoPS': 14},
2010: {'HJK': 1,'KuPS': 2,'TPS': 3,'Honka': 4,'Jaro': 5,'Inter': 6,'TamU': 7,'Haka': 8,'MYPA': 9,'VPS': 10,'FC/AC Oulu': 11,'IFK Mariehamn': 12,'JJK': 13,'Lahti': 14},
2011: {'HJK': 1,'Inter': 2,'JJK': 3,'Honka': 4,'TPS': 5,'KuPS': 6,'IFK Mariehamn': 7,'MYPA': 8,'VPS': 9,'Haka': 10,'Jaro': 11,'RoPS': 12},
2012: {'HJK': 1,'Inter': 2,'TPS': 3,'IFK Mariehamn': 4,'Lahti': 5,'MYPA': 6,'Honka': 7,'VPS': 8,'JJK': 9,'KuPS': 10,'Jaro': 11,'Haka': 12},
2013: {'HJK': 1,'Honka': 2,'VPS': 3,'IFK Mariehamn': 4,'Lahti': 5,'MYPA': 6,'KuPS': 7,'TPS': 8,'Inter': 9,'Jaro': 10,'RoPS': 11,'JJK': 12},
2014: {'HJK': 1,'SJK': 2,'Lahti': 3,'VPS': 4,'IFK Mariehamn': 5,'Jaro': 6,'KuPS': 7,'MYPA': 8,'Inter': 9,'RoPS': 10,'Honka': 11,'TPS': 12},
2015: {'SJK': 1,'RoPS': 2,'HJK': 3,'Inter': 4,'Lahti': 5,'IFK Mariehamn': 6,'HIFK': 7,'Ilves': 8,'KuPS': 9,'VPS': 10,'KooTeePee': 11,'Jaro': 12},
2016: {'IFK Mariehamn': 1,'HJK': 2,'SJK': 3,'VPS': 4,'Ilves': 5,'RoPS': 6,'KuPS': 7,'Lahti': 8,'PS Kemi': 9,'HIFK': 10,'Inter': 11,'PK-35': 12},
2017: {'HJK': 1,'KuPS': 2,'Ilves': 3,'Lahti': 4,'IFK Mariehamn': 5,'SJK': 6,'RoPS': 7,'VPS': 8,'Inter': 9,'PS Kemi': 10,'HIFK': 11,'JJK': 12},
2018: {'HJK': 1,'RoPS': 2,'KuPS': 3,'Honka': 4,'Ilves': 5,'VPS': 6,'Inter': 7,'Lahti': 8,'SJK': 9,'IFK Mariehamn': 10,'TPS': 11,'PS Kemi': 12},
2019: {'KuPS': 1,'Inter': 2,'Honka': 3,'Ilves': 4,'HJK': 5,'IFK Mariehamn': 6,'HIFK': 7,'Lahti': 8,'SJK': 9,'RoPS': 10,'KPV': 11,'VPS': 12}}

# Kirjoita vastauksesi tähän, jossa hyödynnät pandas DataFramea.
# luodaan DataFrame annetusta datasta
data = veikkausliiga
df = pd.DataFrame(data)
df.dtypes

1990    float64
1991    float64
1992    float64
1993    float64
1994    float64
1995    float64
1996    float64
1997    float64
1998    float64
1999    float64
2000    float64
2001    float64
2002    float64
2003    float64
2004    float64
2005    float64
2006    float64
2007    float64
2008    float64
2009    float64
2010    float64
2011    float64
2012    float64
2013    float64
2014    float64
2015    float64
2016    float64
2017    float64
2018    float64
2019    float64
dtype: object

## 4. Säädatan käsittelyä DataFramella (1)

Tee funktio **saa(url)**, joka ottaa argumentikseen datan url:n ja tulostaa vastauksen alla kuvatulla tavalla:
* Lataa datan url:sta pandasin DataFrameen.
* Valitsee kaikki syyskuun 1.-15. päivät, jolloin 'mittari_1 (degC)':n lämpötila on ollut matalampi kuin 'mittari_1 (degC)':n lämpötila 1.9.2000.
* Lajittelee valitut rivit 'mittari_1 (degC)':n lämpötilan mukaan nousevasti.
* Tekee uuden sarakkeen "erotus", joka kertoo 'mittari_1 (degC)':n ja 'mittari_2 (degC)':n lämpötilojen erotuksen itseisarvon.
* Funktio tulostaa edellä muokatusta taulukosta 5 ensimmäistä riviä, jossa ovat sarakkeet 'mittari_1 (degC)', 'mittari_2 (degC)' ja 'erotus'.

Tässä tehtävässä käytetään säähavaintodataa eräältä mittausasemalta vuosilta 1959-2020 seuraavasta url:sta:
url=https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta1/harjoitukset/data_h1_t3.csv

**Esimerkiksi**, funktio saa(url) antaa seuraavan tulosteen:

| |mittari_1 (degC)|mittari_2 (degC)|erotus|
|:---|:---|:---|:---|
|2811           |0.004600          |6.594916  |6.590316|
|21437          |0.005601          |3.937057  |3.931456|
|14130          |0.029420          |0.965881  |0.936460|
|10480          |0.031741          |0.663349  |0.631607|
|245            |0.037996          |1.740839  |1.702842|

**Huom!** Yllä olevassa taulukossa ensimmäinen sarake on rivi-indeksi.

In [219]:
url="https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta1/harjoitukset/data_h1_t3.csv"

def saa(url):

    # funktio lataa dataframen
    df = pd.read_csv(url, encoding='utf-8')

    # Tekee uuden sarakkeen "erotus", joka kertoo 'mittari_1 (degC)':n ja 'mittari_2 (degC)':n lämpötilojen erotuksen itseisarvon.
    df['erotus'] = df['mittari_2 (degC)'] - df['mittari_1 (degC)']
    df['erotus'] = abs(df['erotus'])

    # Funktio etsii 1.9.2000 päivämäärältä 'mittari_1 (degC)':n lukema
    mittari_q = df[(df['Pv']) == 1 & (df['Kk'] == 9) & (df['Vuosi'] == 2000)].index
    mittari_q2 = df.iloc[mittari_q[0], 9]

    # Valitsee kaikki syyskuun 1.-15. päivät, jolloin 'mittari_1 (degC)':n, jolloin lämpötila on ollut matalampi kuin 'mittari_1 (degC)':n lämpötila 1.9.2000.
    df2 = df.loc[(df.Kk==9) & (df.Pv <= 15) & (df['mittari_1 (degC)'] < mittari_q2)]

    # Lajittelee valitut rivit 'mittari_1 (degC)':n lämpötilan mukaan nousevasti.
    df3 = df2.sort_values(by=['mittari_1 (degC)'])

    # Funktio tulostaa edellä muokatusta taulukosta 5 ensimmäistä riviä, jossa ovat sarakkeet 'mittari_1 (degC)', 'mittari_2 (degC)' ja 'erotus'.
    tulos = df3[['mittari_1 (degC)', 'mittari_2 (degC)', 'erotus']]
    print(tulos.head(5))

saa(url)

       mittari_1 (degC)  mittari_2 (degC)    erotus
2811           0.004600          6.594916  6.590316
21437          0.005601          3.937057  3.931456
14130          0.029420          0.965881  0.936460
10480          0.031741          0.663349  0.631607
245            0.037996          1.740839  1.702842

## 5. Säädatan käsittelyä DataFramella (2)


Tee python funktio, joka käyttää argumenttia **url** ja tekee seuraavaa:
* Lataa data DataFrameen.
* Tekee uuden sarakkeen "erotus", joka kertoo 'mittari_1 (degC)':n ja 'mittari_2 (degC)':n lämpötilojen erotuksen itseisarvon.
* Jos "erotus" sarakkeen rivien arvo on pienempi kuin 1.5 astetta, niin kirjoitetaan ko. riville uuteen sarakkeeseen 'virheraja' merkkijono 'in'.
* Valitsee DataFrameen seuraavat kuukaudet: [1, 4, 7, 10].
* Valisee DataFramesta vain ne rivit joiden 'virheraja' sarakkeessa on merkkijono 'in'.
* Valisee uuteen DataFrameen pandasin copy toiminnolla sarakkeet 'Kk', 'erotus' ja 'virheraja'.
* Kirjoittaa uuteen DataFramen sarakkeiden nimiksi 'Month' sarakkeen 'Kk' tilalle, 'Difference' sarakkeen 'erotus' tilalle ja 'Error' sarakkeen 'virheraja' tilalle.
* Tulostaa em. DataFramesta viisi viimeistä riviä.

Tässä tehtävässä **url**=https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta1/harjoitukset/data_h1_t3.csv

Esimerkiksi, komento saa(url) antaa:

| |Month|Difference|Error|
|:--- |:---|:---|:---|
|22206 |10     |0.609291  |in   |
|22212 |10     |0.031468  |in   |
|22214 |10     |1.353995  |in   |
|22215 |10     |1.184691  |in   |
|22283 |1     |0.886008  |in   |

**Huom!** Yllä olevassa taulukossa ensimmäinen sarake on rivi-indeksi.

In [221]:
# Tehtävän datan url:
url="https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta1/harjoitukset/data_h1_t3.csv"

### Palautettavan tehtävän osa alkaa tästä ###
def saa(url):
    
    # Kirjoita vastauksesi tähän:
    
    # Lataa data DataFrameen
    url= "https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta1/harjoitukset/data_h1_t3.csv"
    df = pd.read_csv(url, encoding='utf-8')

    # Tekee uuden sarakkeen "erotus", joka kertoo 'mittari_1 (degC)':n ja 'mittari_2 (degC)':n lämpötilojen erotuksen itseisarvon.
    df['erotus'] = df['mittari_2 (degC)'] - df['mittari_1 (degC)']
    df['erotus'] = abs(df['erotus'])

    # Jos "erotus" sarakkeen rivien arvo on pienempi kuin 1.5 astetta, niin kirjoitetaan ko. riville uuteen sarakkeeseen 'virheraja' merkkijono 'in'.
    df['virheraja'] = df['erotus']
    df.loc[df['erotus'] < 1.5, 'virheraja'] = "in"

    # Valitsee DataFrameen seuraavat kuukaudet: [1, 4, 7, 10].
    df2 = df[df['Kk'].isin([1, 4, 7, 10])]

    # Valitsee DataFramesta vain ne rivit joiden 'virheraja' sarakkeessa on merkkijono 'in'.
    df3 = df2[df2['virheraja'].isin(['in'])]

    # Valitsee uuteen DataFrameen pandasin copy toiminnolla sarakkeet 'Kk', 'erotus' ja 'virheraja'.
    df3_copy = df3.copy()
    df3_copy = df3_copy[['Kk','erotus','virheraja']]

    # Kirjoittaa uuteen DataFramen sarakkeiden nimiksi 'Month' sarakkeen 'Kk' tilalle, 'Difference' sarakkeen 'erotus' tilalle ja 'Error' sarakkeen 'virheraja' tilalle.
    df3_copy.rename(columns = {'Kk':'Month'}, inplace = True)
    df3_copy.rename(columns = {'erotus':'Difference'}, inplace = True)
    df3_copy.rename(columns = {'virheraja':'Error'}, inplace = True)

    tulos = df3_copy
    
    # Vastauksesi tulostetaan. Älä käytä muita print toimintoja kuin tässä alla.
    print(tulos.tail(5))
    
### Palautettavan tehtävän osa päättyy tähän.   

    
# Kokeile tekemääsi funktiota:
saa(url)

       Month  Difference Error
22206     10    0.609291    in
22212     10    0.031468    in
22214     10    1.353995    in
22215     10    1.184691    in
22283      1    0.886008    in

In [215]:
# Lataa data DataFrameen
url= "https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta1/harjoitukset/data_h1_t3.csv"
df = pd.read_csv(url, encoding='utf-8')

# Tekee uuden sarakkeen "erotus", joka kertoo 'mittari_1 (degC)':n ja 'mittari_2 (degC)':n lämpötilojen erotuksen itseisarvon.
df['erotus'] = df['mittari_2 (degC)'] - df['mittari_1 (degC)']
df['erotus'] = abs(df['erotus'])

# Jos "erotus" sarakkeen rivien arvo on pienempi kuin 1.5 astetta, niin kirjoitetaan ko. riville uuteen sarakkeeseen 'virheraja' merkkijono 'in'.
df['virheraja'] = df['erotus']
df.loc[df['erotus'] < 1.5, 'virheraja'] = "in"

# Valitsee DataFrameen seuraavat kuukaudet: [1, 4, 7, 10].
df2 = df[df['Kk'].isin([1, 4, 7, 10])]

# Valitsee DataFramesta vain ne rivit joiden 'virheraja' sarakkeessa on merkkijono 'in'.
df3 = df2[df2['virheraja'].isin(['in'])]

# Valitsee uuteen DataFrameen pandasin copy toiminnolla sarakkeet 'Kk', 'erotus' ja 'virheraja'.
df3_copy = df3.copy()
df3_copy = df3_copy[['Kk','erotus','virheraja']]

# Kirjoittaa uuteen DataFramen sarakkeiden nimiksi 'Month' sarakkeen 'Kk' tilalle, 'Difference' sarakkeen 'erotus' tilalle ja 'Error' sarakkeen 'virheraja' tilalle.
df3_copy.rename(columns = {'Kk':'Month'}, inplace = True)
df3_copy.rename(columns = {'erotus':'Difference'}, inplace = True)
df3_copy.rename(columns = {'virheraja':'Error'}, inplace = True)

df3_copy.tail(5)

       Month  Difference Error
22206     10    0.609291    in
22212     10    0.031468    in
22214     10    1.353995    in
22215     10    1.184691    in
22283      1    0.886008    in